title: Francisco J Torres
description: Data Analyst | Data Scientist 
logo: "/assets/profile.jpg" # Change the filename in your assets folder to match this!

# Essential for Chirpy
url: "https://franciscojtorres.github.io" # Replace with your actual GitHub URL
baseurl: ""

# Theme Settings
remote_theme: cotes2020/jekyll-theme-chirpy
google_analytics: G-7NYB90WTT1

plugins:
  - jekyll-remote-theme
# https
#  pages-themes/minimal@v0.2.0
